version: '3'

services:

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: mondegc_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - mailhog

  mysql:
    image: mysql:8.0
    container_name: mondegc_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/entrypoint:/docker-entrypoint-initdb.d
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=IGNORE_SPACE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mondegc_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    links:
      - mysql

  mailhog:
    image: mailhog/mailhog
    container_name: mondegc_mailhog
    logging:
      driver: "none"  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
