version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mondegc_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - mailhog

  mysql:
    image: mysql:8.0
    container_name: mondegc_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mondegc

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mondegc_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 50M
    ports:
      - "8080:80"
    links:
      - mysql

  mailhog:
    image: mailhog/mailhog
    container_name: mondegc_mailhog
    logging:
      driver: "none"  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
